### ISSUE TITLE
rotationSpeed is 0 on service restart

### ISSUE THREAD

**Issue by rsporny** [phenotypic/homebridge-web-fan#1]
Hey!
Thanks for sharing this great plugin. I noticed that when `rotationSpeed` is set to `true` homekit show 0% on first boot of accessory, e.g. after power loss. I'm using it for my ventilation system and after power loss it recovers to the previous rotation speed so I think this plugin could consume that value to show it correctly in homekit - what do you think?
```
{
    "currentState": INT_VALUE,
    "rotationSpeed": INT_VALUE     <--- to add
}
```

**Comment by phenotypic** [comment]
Hi there, would you be able to run homebridge in debug mode and verify you receive a `Updated rotationSpeed to: INT` message when you get shown 0%?

As long as `rotationSpeed` is set to `true`, you _should_ get a poll on startup as well as at each poll interval (5 minutes by default) - as per lines `101` to `104` in the `index.js`

**Comment by rsporny** [comment]
You're right, my api didn't return `rotationSpeed`, only allowed to set it. Thanks!
