### ISSUE TITLE
Basic fan control

### ISSUE THREAD

**Issue by ChopsKingsland** [phenotypic/homebridge-web-fan#2]
Is there a way to have rotation as an on/off, not rotation. And, is there a way to have fan speed as set speeds (i.e. 0, 1, 2, 3) as my fan only has 3 speeds (a bit like thermostats, below)
![image](https://user-images.githubusercontent.com/18499854/120621544-ddf4bc00-c455-11eb-8d5f-b1cfc9963f67.png)

Thanks in advance!

**Comment by phenotypic** [comment]
Hi there, thanks for opening this issue. Unfortunately I'm not actively maintaining this plugin at the moment as I have no devices that use it. However, looking at the [RotationSpeed docs](https://developers.homebridge.io/#/characteristic/RotationSpeed), it seems like the characteristic can only be set as a percentage and not as set speeds.

You are more than welcome to fork the plugin and attempt this yourself though!

**Comment by ChopsKingsland** [comment]
I have created a fork, but realised it doesn't follow the default structure of a Homebridge plugin... it should be like 
![image](https://user-images.githubusercontent.com/18499854/120853019-f9091e00-c572-11eb-95ff-40368728c16f.png)

Do you happen to have the plugin in this form?
